name: CI/CD Pipeline with Minikube (docker driver)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-req:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Minikube and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack socat ebtables iptables
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
    
  minikube-setup:
    needs: pre-req
    runs-on: ubuntu-latest

    steps:
      - name: Start Docker service
        run: |
          sudo systemctl start docker

      - name: Start Minikube (docker driver, force root, extra resources)
        run: |
          sudo minikube start --driver=docker --force --cpus=2 --memory=4096mb || true
          minikube status
          minikube logs

      - name: Set docker-env for Minikube
        run: |
          eval $(minikube -p minikube docker-env)

  docker-build-and-deploy:
    needs: pre-req  minikube-setup
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image in Minikube
        run: |
          docker build -t devops-demo .

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/devops-demo-deployment

      - name: Test service response
        run: |
          NODE_PORT=$(kubectl get service/devops-demo-service -o=jsonpath='{.spec.ports[0].nodePort}')
          MINIKUBE_IP=$(minikube ip)
          sleep 10
          curl --retry 10 --retry-delay 5 "http://$MINIKUBE_IP:$NODE_PORT" | grep "Hello, DevOps World!"

      - name: Clean up
        if: always()
        run: |
          sudo minikube delete