name: CI/CD Pipeline with Minikube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  minikube-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          sudo minikube start --driver=docker
          minikube status

      - name: Set Minikube docker-env
        run: |
          eval $(minikube -p minikube docker-env)

      - name: Build Docker image inside Minikube
        run: |
          docker build -t devops-demo .

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/devops-demo-deployment

      - name: Test service response
        run: |
          # Get NodePort
          NODE_PORT=$(kubectl get service/devops-demo-service -o=jsonpath='{.spec.ports[0].nodePort}')
          # Get Minikube IP
          MINIKUBE_IP=$(minikube ip)
          # Wait for app to be ready
          sleep 10
          curl --retry 10 --retry-delay 5 "http://$MINIKUBE_IP:$NODE_PORT" | grep "Hello, DevOps World!"

      - name: Clean up
        if: always()
        run: |
          minikube delete