name: CI/CD Pipeline with Minikube (none driver + cri-dockerd)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack curl socat ebtables iptables golang-go make

      - name: Install crictl
        run: |
          VERSION="v1.29.0"
          curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xzvf crictl-$VERSION-linux-amd64.tar.gz
          rm crictl-$VERSION-linux-amd64.tar.gz

      - name: Install cri-dockerd
        run: |
          git clone https://github.com/Mirantis/cri-dockerd.git
          cd cri-dockerd
          make cri-dockerd
          sudo install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
          sudo cp -a packaging/systemd/* /etc/systemd/system/
          sudo sed -i 's:/usr/bin/cri-dockerd:/usr/local/bin/cri-dockerd:' /etc/systemd/system/cri-dockerd.service
          sudo systemctl daemon-reexec
          sudo systemctl daemon-reload
          sudo systemctl enable cri-dockerd.service
          sudo systemctl start cri-dockerd.service

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          rm minikube-linux-amd64

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          rm kubectl

      - name: Start Minikube (none driver)
        run: |
          sudo minikube start --driver=none
          sudo minikube update-context
          kubectl cluster-info
          kubectl get nodes

  docker-build-and-deploy:
    needs: setup-minikube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker env to Minikube
        run: |
          eval $(minikube docker-env)

      - name: Build Docker image inside Minikube
        run: |
          docker build -t devops-demo .

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/devops-demo-deployment

      - name: Test service response
        run: |
          NODE_PORT=$(kubectl get service/devops-demo-service -o=jsonpath='{.spec.ports[0].nodePort}')
          MINIKUBE_IP=$(minikube ip)
          sleep 10
          curl --retry 10 --retry-delay 5 "http://$MINIKUBE_IP:$NODE_PORT" | grep "Hello, DevOps World!"

      - name: Clean up Minikube
        if: always()
        run: |
          sudo minikube delete